env:
  browser: true
  commonjs: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
plugins:
  - '@typescript-eslint'
rules:
  "@typescript-eslint/no-namespace": off
  "@typescript-eslint/no-explicit-any": off
  "@typescript-eslint/no-inferrable-types": off
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - never
