import sourcemaps from 'rollup-plugin-sourcemaps'
import resolve from 'rollup-plugin-node-resolve'
import * as path from 'path'

const src = sourcemaps()

export default {
  input: 'module/index.js',
  output: {
    file: 'dist/elt.js',
    sourcemap: true,
    name: 'elt',
    format: 'umd'
  },
  plugins: [
    {
      name: 'custom-transform',
      load(id) {
        return src.load(id)
          .then(res => {
            if (id.match(/\/module\//)) {
              // We have to do this ugly swith, otherwise rollup bugs and generates
              // incorrect javascript.
              // Anyways, this was generated by typescript with the "namespace o",
              // and this whole checking mechanics for the existence of o is actually
              // useless since we, the programmer, *know* that it does.
              res.code = res.code.replace('o = o || (o = {})', 'o /*o || (o = {*/')
                // .replace(/^\/\/# (.*)$/g, '//. \\1')
            }
            return res
          })
      }
    },
    resolve(),
  ]
}
