import "elt/ui"
import { $click, $scrollable, App, node_append, Service, view, css } from "elt"
import { e2Root } from "./e2.tsx"
import type { ParsedDoc } from "./macro.ts"

// Registers every docs/md/**/*.md file as a watched bundler dependency — generated by elt_md()
// itself (do not hand-edit; gitignored). See specs/markdown-docs.md, "File registration".
import "./deps"
import { elt_md } from "./macro.ts" with { type: "macro" }

const docs = await elt_md()
const docsByName = new Map(docs.map((d) => [d.name, d]))

export const app = new App()

// One shared page class for every markdown-sourced page, not one class/route per file — a class
// *expression* generated per page inside a loop can't carry `@view` (`experimentalDecorators`
// rejects decorators on non-declaration classes — confirmed by testing against an earlier
// per-file-class version of this). See specs/markdown-docs.md, "Routing".
class MdPage extends Service({}, {} as { name: string }) {
  @view
  Content() {
    const oo_name = this.srv.param_soft("name", "index")
    const oo_doc = oo_name.tf((name): ParsedDoc => docsByName.get(name) ?? docsByName.get("index")!)
    return <e-block typographic pad>{oo_doc.tf((doc) => e2Root(doc))}</e-block>
  }
}

export const routes = app.setupRouter({
  home: ["", () => MdPage, { defaults: { name: "index" } }],
  docs: ["/docs/:name", () => MdPage],
})

function widget_nav() {
  return <e-column touching align="stretch">
    {docs.map((doc) => <button>
      {$click(() => routes.docs.activate({ name: doc.name }))}
      {doc.frontmatter.title ?? doc.name}
    </button>)}
  </e-column>
}

const cls_main = css`.main {
  height: 100%;
  width: 100%;
  overflow: hidden;
}`

node_append(document.body, <e-row align="stretch" class={cls_main}>
  {widget_nav()}
  <e-column grow>
    {$scrollable}
    {app.DisplayView("Content")}
  </e-column>
</e-row>)

