// Router loader for the docs app. Tracked and hand-written — everything that depends on the
// current `docs/md/**/*.md` tree (the actual route table and menu, in `routes.generated.ts`, plus
// the bundler-watched imports that make this file reload when a doc changes) is generated by
// `elt_md()` (see specs/markdown-docs-reloaded.md, "Macro").
//
// Registers every docs/md/**/*.md file as a watched bundler dependency — generated by elt_md()
// itself (do not hand-edit; gitignored). A macro's own `Bun.file()` reads do not count as bundler
// dependencies, so this side-effect-only import is what makes this file (and therefore the fresh
// `routes.generated.ts` write below) actually happen when a `.md` file changes.
import "./md-deps"
import { elt_md } from "./macro.ts" with { type: "macro" }

await elt_md()

export { routes, menu } from "./routes.generated.ts"
